{'name': 'Trainee Master',
 'version': '0.1',
 'author': 'Srija',
 'category': 'HRM',
 'website': 'http://www.openerp.com',
 'description': """ """,
 'depends': ['base',
             'kg_division_master',
             'kg_location_master',
             'hr',
             ],
 'data': ['kg_trainee.xml'],
 'auto_install': False,
 'installable': True}
